
project_id = "e018c1f7-6eb1-4acf-992c-e21876114c0e"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
external_url = "http://127.0.0.1:54321"
jwt_expiry = 3600
refresh_token_rotation_enabled = true
refresh_token_reuse_interval = 10
enable_signup = true

[db]
port = 54322

[functions.generate-did]
verify_jwt = true

[functions.submit-ion-operation]
verify_jwt = true

[storage]
enabled = true
port = 54323
file_size_limit = "50MiB"
